# Generated by Django 3.0.2 on 2020-07-09 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobs',
            name='topic',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
