# Generated by Django 3.0.2 on 2020-07-10 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_auto_20200711_0147'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('topic', models.CharField(max_length=200, null=True)),
                ('summary', models.TextField(null=True)),
            ],
        ),
    ]
