# Generated by Django 3.0.2 on 2020-07-10 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_certificates'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificates',
            name='proof',
            field=models.ImageField(null=True, upload_to='Images/'),
        ),
    ]
