# Generated by Django 3.0.2 on 2020-07-10 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_certificates_proof'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificates',
            name='proof',
            field=models.URLField(max_length=300, null=True),
        ),
    ]
