# Generated by Django 3.0.2 on 2020-07-10 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0006_auto_20200711_0358'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificates',
            name='ref',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
