# Generated by Django 3.0.2 on 2020-08-02 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0008_certificates_issue'),
    ]

    operations = [
        migrations.CreateModel(
            name='Publications',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('topic', models.CharField(max_length=200, null=True)),
                ('summary', models.TextField(null=True)),
            ],
        ),
    ]
