# Generated by Django 3.0.2 on 2020-08-02 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0009_publications'),
    ]

    operations = [
        migrations.AddField(
            model_name='publications',
            name='proof',
            field=models.URLField(max_length=300, null=True),
        ),
    ]
